### ISSUE TITLE
Integration and other types of modules and frameworks 

### ISSUE THREAD

**Issue by Maycomsantos** [lamaralmp/mp-ecommerce-php#5]
Olá, tudo bem ? Vi esse repositório e achei bem interessante, pretendo fazer um Fork desse projeto e brincar um pouco com ele e fazer outros tipos de integração me baseando no Layout que você criou. Quero saber se poderei adaptar para Vue + Laravel e fazer um vídeo pro meu canal sobre isso. 

Quem sabe poder lançar também essa Loja virtual no Github e orientar outras pessoas a montarem também. 

Pretendo fazer uma loja na qual contenha esses produtos e as pessoas simulem uma compra, como se tivessem usando no dia a dia.

**Comment by lamaralmp** [comment]
Olá, tudo bem e você?
Muito bom, fique a vontade para usar esse código. Também te recomendo o [repositório mais atualizado](https://github.com/mercadopago/card-payment-sample/tree/master/server/php) que publicamos. Também tem um layout moderno.
Qualquer dúvida no processo de integração pode consultar nossa documentação no [Devsite](https://www.mercadopago.com.br/developers/pt/guides) do Mercado Pago ou através do [Suporte](https://www.mercadopago.com.br/developers/pt/support).

**Comment by Maycomsantos** [comment]
Opa ! Perfeito, pode deixar.
